// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/definitions/definitions.proto

package definitions

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	LastUpdate           uint32   `protobuf:"varint,3,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	Expiration           uint32   `protobuf:"varint,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Item) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Item) GetLastUpdate() uint32 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *Item) GetExpiration() uint32 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type AddRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type CompareAndSwapRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareAndSwapRequest) Reset()         { *m = CompareAndSwapRequest{} }
func (m *CompareAndSwapRequest) String() string { return proto.CompactTextString(m) }
func (*CompareAndSwapRequest) ProtoMessage()    {}
func (*CompareAndSwapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{2}
}

func (m *CompareAndSwapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareAndSwapRequest.Unmarshal(m, b)
}
func (m *CompareAndSwapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareAndSwapRequest.Marshal(b, m, deterministic)
}
func (m *CompareAndSwapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareAndSwapRequest.Merge(m, src)
}
func (m *CompareAndSwapRequest) XXX_Size() int {
	return xxx_messageInfo_CompareAndSwapRequest.Size(m)
}
func (m *CompareAndSwapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareAndSwapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompareAndSwapRequest proto.InternalMessageInfo

func (m *CompareAndSwapRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type SetRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{3}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type DeleteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllRequest) Reset()         { *m = DeleteAllRequest{} }
func (m *DeleteAllRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllRequest) ProtoMessage()    {}
func (*DeleteAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{5}
}

func (m *DeleteAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllRequest.Unmarshal(m, b)
}
func (m *DeleteAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllRequest.Merge(m, src)
}
func (m *DeleteAllRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllRequest.Size(m)
}
func (m *DeleteAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllRequest proto.InternalMessageInfo

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{6}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Reply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Item                 *Item    `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{7}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Reply) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type AddServerRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddServerRequest) Reset()         { *m = AddServerRequest{} }
func (m *AddServerRequest) String() string { return proto.CompactTextString(m) }
func (*AddServerRequest) ProtoMessage()    {}
func (*AddServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{8}
}

func (m *AddServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddServerRequest.Unmarshal(m, b)
}
func (m *AddServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddServerRequest.Marshal(b, m, deterministic)
}
func (m *AddServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddServerRequest.Merge(m, src)
}
func (m *AddServerRequest) XXX_Size() int {
	return xxx_messageInfo_AddServerRequest.Size(m)
}
func (m *AddServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddServerRequest proto.InternalMessageInfo

func (m *AddServerRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DropServerRequest struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropServerRequest) Reset()         { *m = DropServerRequest{} }
func (m *DropServerRequest) String() string { return proto.CompactTextString(m) }
func (*DropServerRequest) ProtoMessage()    {}
func (*DropServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{9}
}

func (m *DropServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropServerRequest.Unmarshal(m, b)
}
func (m *DropServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropServerRequest.Marshal(b, m, deterministic)
}
func (m *DropServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropServerRequest.Merge(m, src)
}
func (m *DropServerRequest) XXX_Size() int {
	return xxx_messageInfo_DropServerRequest.Size(m)
}
func (m *DropServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropServerRequest proto.InternalMessageInfo

func (m *DropServerRequest) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type GetServersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServersRequest) Reset()         { *m = GetServersRequest{} }
func (m *GetServersRequest) String() string { return proto.CompactTextString(m) }
func (*GetServersRequest) ProtoMessage()    {}
func (*GetServersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{10}
}

func (m *GetServersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServersRequest.Unmarshal(m, b)
}
func (m *GetServersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServersRequest.Marshal(b, m, deterministic)
}
func (m *GetServersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServersRequest.Merge(m, src)
}
func (m *GetServersRequest) XXX_Size() int {
	return xxx_messageInfo_GetServersRequest.Size(m)
}
func (m *GetServersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServersRequest proto.InternalMessageInfo

type ServerList struct {
	Servers              []string `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerList) Reset()         { *m = ServerList{} }
func (m *ServerList) String() string { return proto.CompactTextString(m) }
func (*ServerList) ProtoMessage()    {}
func (*ServerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{11}
}

func (m *ServerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerList.Unmarshal(m, b)
}
func (m *ServerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerList.Marshal(b, m, deterministic)
}
func (m *ServerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerList.Merge(m, src)
}
func (m *ServerList) XXX_Size() int {
	return xxx_messageInfo_ServerList.Size(m)
}
func (m *ServerList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerList.DiscardUnknown(m)
}

var xxx_messageInfo_ServerList proto.InternalMessageInfo

func (m *ServerList) GetServers() []string {
	if m != nil {
		return m.Servers
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "definitions.Item")
	proto.RegisterType((*AddRequest)(nil), "definitions.AddRequest")
	proto.RegisterType((*CompareAndSwapRequest)(nil), "definitions.CompareAndSwapRequest")
	proto.RegisterType((*SetRequest)(nil), "definitions.SetRequest")
	proto.RegisterType((*DeleteRequest)(nil), "definitions.DeleteRequest")
	proto.RegisterType((*DeleteAllRequest)(nil), "definitions.DeleteAllRequest")
	proto.RegisterType((*GetRequest)(nil), "definitions.GetRequest")
	proto.RegisterType((*Reply)(nil), "definitions.Reply")
	proto.RegisterType((*AddServerRequest)(nil), "definitions.AddServerRequest")
	proto.RegisterType((*DropServerRequest)(nil), "definitions.DropServerRequest")
	proto.RegisterType((*GetServersRequest)(nil), "definitions.GetServersRequest")
	proto.RegisterType((*ServerList)(nil), "definitions.ServerList")
}

func init() { proto.RegisterFile("grpc/definitions/definitions.proto", fileDescriptor_671b7d4d1004a799) }

var fileDescriptor_671b7d4d1004a799 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5b, 0x8b, 0xd3, 0x40,
	0x14, 0xde, 0x6c, 0xba, 0x2d, 0x3d, 0xeb, 0x42, 0x3b, 0xde, 0x42, 0xc1, 0x52, 0x07, 0x94, 0x82,
	0xb2, 0xc2, 0xd6, 0x27, 0x1f, 0x64, 0xa3, 0x0b, 0x51, 0xf0, 0x29, 0xc1, 0x1f, 0x30, 0x76, 0x8e,
	0x35, 0x98, 0xcb, 0x38, 0x33, 0xad, 0xf6, 0x9f, 0xfb, 0x28, 0x93, 0x4b, 0x73, 0x6b, 0x5c, 0xfa,
	0x96, 0x73, 0xf9, 0xce, 0xf7, 0xcd, 0xf9, 0x0e, 0x01, 0xba, 0x91, 0x62, 0xfd, 0x86, 0xe3, 0xf7,
	0x30, 0x09, 0x75, 0x98, 0x26, 0xaa, 0xfe, 0x7d, 0x2d, 0x64, 0xaa, 0x53, 0x72, 0x59, 0x4b, 0xd1,
	0x04, 0x06, 0x9f, 0x35, 0xc6, 0x64, 0x02, 0xf6, 0x4f, 0xdc, 0x3b, 0xd6, 0xc2, 0x5a, 0x8e, 0x7d,
	0xf3, 0x49, 0x1e, 0xc1, 0xc5, 0x8e, 0x45, 0x5b, 0x74, 0xce, 0x17, 0xd6, 0xf2, 0x81, 0x9f, 0x07,
	0x64, 0x0e, 0x10, 0x31, 0xa5, 0xbf, 0x0a, 0xce, 0x34, 0x3a, 0xf6, 0xc2, 0x5a, 0x5e, 0xf9, 0xb5,
	0x8c, 0xa9, 0xe3, 0x1f, 0x11, 0x4a, 0x66, 0xc6, 0x3b, 0x83, 0xbc, 0x5e, 0x65, 0xe8, 0x0a, 0xc0,
	0xe5, 0xdc, 0xc7, 0x5f, 0x5b, 0x54, 0x9a, 0xbc, 0x80, 0x41, 0xa8, 0x31, 0xce, 0x68, 0x2f, 0x6f,
	0xa6, 0xd7, 0x75, 0xb1, 0x46, 0x96, 0x9f, 0x95, 0xe9, 0x7b, 0x78, 0xfc, 0x31, 0x8d, 0x05, 0x93,
	0xe8, 0x26, 0x3c, 0xf8, 0xcd, 0xc4, 0x89, 0xf8, 0x15, 0x40, 0x80, 0xfa, 0x44, 0xd0, 0x73, 0xb8,
	0xba, 0xc3, 0x08, 0x35, 0x96, 0xb8, 0xce, 0x8a, 0x28, 0x81, 0x49, 0xde, 0xe2, 0x46, 0x51, 0xd1,
	0x45, 0xe7, 0x00, 0x5e, 0xc5, 0xd5, 0xc5, 0x7c, 0x82, 0x0b, 0x1f, 0x45, 0xb4, 0x27, 0x0e, 0x8c,
	0x62, 0x54, 0x8a, 0x6d, 0xb0, 0x28, 0x97, 0xe1, 0x41, 0xe0, 0xf9, 0xff, 0x05, 0xbe, 0x86, 0x89,
	0xcb, 0x79, 0x80, 0x72, 0x87, 0xb2, 0xe4, 0x73, 0x60, 0xc4, 0x38, 0x97, 0xa8, 0x54, 0x39, 0xb4,
	0x08, 0xe9, 0x2b, 0x98, 0xde, 0xc9, 0x54, 0x34, 0xdb, 0x9f, 0xc0, 0x50, 0x65, 0x89, 0xa2, 0xbb,
	0x88, 0xe8, 0x43, 0x98, 0x7a, 0xa8, 0xf3, 0x5e, 0x55, 0xbe, 0xec, 0xa5, 0xd9, 0xa2, 0xc9, 0x7c,
	0x09, 0x73, 0xa6, 0xbc, 0xd9, 0x30, 0xd9, 0x86, 0xa9, 0x08, 0x6f, 0xfe, 0xda, 0x30, 0xe2, 0x72,
	0xcd, 0xd6, 0x3f, 0x90, 0xbc, 0x05, 0xdb, 0xe5, 0x9c, 0x3c, 0x6d, 0xbc, 0xa1, 0x3a, 0x80, 0x19,
	0x69, 0x14, 0xb2, 0xc5, 0xd0, 0x33, 0x83, 0x0a, 0x50, 0xb7, 0x50, 0x95, 0x83, 0x3d, 0xa8, 0x77,
	0x30, 0xcc, 0xdd, 0x20, 0xb3, 0x46, 0xbd, 0xe1, 0x62, 0x0f, 0xf6, 0x16, 0xc6, 0x07, 0x27, 0xc9,
	0xb3, 0x23, 0xf0, 0xca, 0xe1, 0x7e, 0xcd, 0x5e, 0x47, 0xb3, 0x77, 0x9f, 0xe6, 0x5b, 0x18, 0x1f,
	0x3c, 0x6c, 0xf1, 0xb6, 0xbd, 0xed, 0x99, 0xe0, 0x65, 0xf7, 0x56, 0x58, 0x45, 0xe6, 0x6d, 0xfa,
	0xa6, 0x87, 0xb3, 0xf6, 0x4a, 0x4b, 0x3b, 0xe9, 0x19, 0xf9, 0x00, 0x50, 0x1d, 0x48, 0x6b, 0x50,
	0xe7, 0x72, 0x8e, 0x8b, 0xf9, 0x36, 0xcc, 0xfe, 0x30, 0xab, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x82, 0xd0, 0x5e, 0xf5, 0x87, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DrcacheClient is the client API for Drcache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DrcacheClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Reply, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*Reply, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Reply, error)
	DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*Reply, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Reply, error)
	AddServer(ctx context.Context, in *AddServerRequest, opts ...grpc.CallOption) (*Reply, error)
	GetServers(ctx context.Context, in *GetServersRequest, opts ...grpc.CallOption) (*ServerList, error)
	DropServer(ctx context.Context, in *DropServerRequest, opts ...grpc.CallOption) (*Reply, error)
}

type drcacheClient struct {
	cc *grpc.ClientConn
}

func NewDrcacheClient(cc *grpc.ClientConn) DrcacheClient {
	return &drcacheClient{cc}
}

func (c *drcacheClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/definitions.drcache/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drcacheClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/definitions.drcache/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drcacheClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/definitions.drcache/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drcacheClient) DeleteAll(ctx context.Context, in *DeleteAllRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/definitions.drcache/DeleteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drcacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/definitions.drcache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drcacheClient) AddServer(ctx context.Context, in *AddServerRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/definitions.drcache/AddServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drcacheClient) GetServers(ctx context.Context, in *GetServersRequest, opts ...grpc.CallOption) (*ServerList, error) {
	out := new(ServerList)
	err := c.cc.Invoke(ctx, "/definitions.drcache/GetServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drcacheClient) DropServer(ctx context.Context, in *DropServerRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/definitions.drcache/DropServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrcacheServer is the server API for Drcache service.
type DrcacheServer interface {
	Add(context.Context, *AddRequest) (*Reply, error)
	Set(context.Context, *SetRequest) (*Reply, error)
	Delete(context.Context, *DeleteRequest) (*Reply, error)
	DeleteAll(context.Context, *DeleteAllRequest) (*Reply, error)
	Get(context.Context, *GetRequest) (*Reply, error)
	AddServer(context.Context, *AddServerRequest) (*Reply, error)
	GetServers(context.Context, *GetServersRequest) (*ServerList, error)
	DropServer(context.Context, *DropServerRequest) (*Reply, error)
}

// UnimplementedDrcacheServer can be embedded to have forward compatible implementations.
type UnimplementedDrcacheServer struct {
}

func (*UnimplementedDrcacheServer) Add(ctx context.Context, req *AddRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedDrcacheServer) Set(ctx context.Context, req *SetRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedDrcacheServer) Delete(ctx context.Context, req *DeleteRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedDrcacheServer) DeleteAll(ctx context.Context, req *DeleteAllRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAll not implemented")
}
func (*UnimplementedDrcacheServer) Get(ctx context.Context, req *GetRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedDrcacheServer) AddServer(ctx context.Context, req *AddServerRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddServer not implemented")
}
func (*UnimplementedDrcacheServer) GetServers(ctx context.Context, req *GetServersRequest) (*ServerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServers not implemented")
}
func (*UnimplementedDrcacheServer) DropServer(ctx context.Context, req *DropServerRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropServer not implemented")
}

func RegisterDrcacheServer(s *grpc.Server, srv DrcacheServer) {
	s.RegisterService(&_Drcache_serviceDesc, srv)
}

func _Drcache_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrcacheServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.drcache/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrcacheServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drcache_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrcacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.drcache/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrcacheServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drcache_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrcacheServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.drcache/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrcacheServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drcache_DeleteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrcacheServer).DeleteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.drcache/DeleteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrcacheServer).DeleteAll(ctx, req.(*DeleteAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drcache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrcacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.drcache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrcacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drcache_AddServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrcacheServer).AddServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.drcache/AddServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrcacheServer).AddServer(ctx, req.(*AddServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drcache_GetServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrcacheServer).GetServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.drcache/GetServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrcacheServer).GetServers(ctx, req.(*GetServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drcache_DropServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrcacheServer).DropServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.drcache/DropServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrcacheServer).DropServer(ctx, req.(*DropServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Drcache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "definitions.drcache",
	HandlerType: (*DrcacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Drcache_Add_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Drcache_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Drcache_Delete_Handler,
		},
		{
			MethodName: "DeleteAll",
			Handler:    _Drcache_DeleteAll_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Drcache_Get_Handler,
		},
		{
			MethodName: "AddServer",
			Handler:    _Drcache_AddServer_Handler,
		},
		{
			MethodName: "GetServers",
			Handler:    _Drcache_GetServers_Handler,
		},
		{
			MethodName: "DropServer",
			Handler:    _Drcache_DropServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/definitions/definitions.proto",
}
